version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "app-composer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18dxk0fa350bx"
s3_prefix = "app-composer"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
